// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.io.Serializable;
import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Categoria implements Serializable{
	private String codigo;
	private String desc;
	private int porcentajeRecargo;
	
	public Categoria(String codigo, String desc, int porcentajeRecargo) {
		super();
		this.codigo = codigo;
		this.desc = desc;
		this.porcentajeRecargo = porcentajeRecargo;
	}

	public String getCodigo() {
		String aux=this.codigo;
		return aux;
	}

	public String getDesc() {
		String aux=this.desc;
		return aux;
	}

	public void setCodigo(String codigo) {
		String aux = codigo;
		this.codigo = aux;
	}

	public void setDesc(String desc) {
		String aux = desc;
		this.desc = aux;
	}

	public int getPorcentajeRecargo() {
		int aux=this.porcentajeRecargo;
		return aux;
	}

	public void setPorcentajeRecargo(int porcentajeRecargo) {
		int aux = porcentajeRecargo;
		this.porcentajeRecargo = aux;
	}

	@Override
	public String toString() {
		return "Categoria "+ codigo + ", " + desc ;
	}
	
	
	
	

}
