// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.io.Serializable;
import java.util.*;

/************************************************************/
/**
 * 
 */
public class Cliente extends miLibreria.objetos.Persona implements Serializable{
	private static final long serialVersionUID = 12344722544367L;
	private TipoCarnet carnetConducir;
	private String nTarjetaCliente;

	/**
	 * Constructor de cliente completo
	 * @param ap1 String Primer Apellido
	 * @param ap2 String Segundo Apellido
	 * @param nombre String de Nombre de la Persona
	 * @param fechaNac Dato tipo GregorianCalendar con la fecha de nacimiento
	 * @param dni String con el DNI del usuario
	 * @param carnetConducir objeto TipoCarnet
	 * @param nTarjetaCliente String nTarjetaCliente
	 */
	public Cliente(String ap1, String ap2, String nombre, GregorianCalendar fechaNac, String dni,TipoCarnet carnetConducir,String nTarjetaCliente) {
		super(ap1, ap2, nombre, fechaNac, dni);
		// TODO Auto-generated constructor stub
		this.carnetConducir = carnetConducir;
		this.nTarjetaCliente = nTarjetaCliente;
	}

	public TipoCarnet getCarnetConducir() {
		TipoCarnet aux=this.carnetConducir;
		return aux;
	}

	public String getnTarjetaCliente() {
		String aux=this.nTarjetaCliente;
		return aux;
	}

	public void setCarnetConducir(TipoCarnet carnetConducir) {
		TipoCarnet aux = carnetConducir;
		this.carnetConducir = aux;	
	}

	public void setnTarjetaCliente(String nTarjetaCliente) {
		String aux = nTarjetaCliente;
		this.nTarjetaCliente = aux;	
	}

	@Override
	public String toString() {
		return super.toString()+", Carnet : " + carnetConducir + ", Ncliente cliente : " + nTarjetaCliente;
	}
	
	
	
	
}
