// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.util.Calendar;
import java.util.GregorianCalendar;

/************************************************************/
/**
 * 
 */
public class CocheElectrico extends Electrico {
	private static final long serialVersionUID = 12345435667567L;
	private int n_plazas;
	private String tipo;
	
	private Double precioDiario = 50.0;
	


	/**
	 * Construcor completo de coche electrico
	 * @param matricula String matriculo vehiculo.
	 * @param marca String marca vehículo.
	 * @param modelo String modelo vehículo.
	 * @param color String color vehículo.
	 * @param fechaAlta Calendar fecha de alta del vehículo en el concesionario.
	 * @param kms Int kilometros que lleva recorrido el vehículo.
	 * @param categoria Categoría categoria del vehículo.
	 * @param oficina Oficina donde se encuentra el vehículo.
	 * @param alquilado Boolean si está o no alquilado.
	 * @param consumo Double del consumo del vehicculo por km.
	 * @param potencia Int potencia del vehículo.
	 * @param nivel_emison String nivel de emision.
	 * @param n_plazas int numero de plazas que tiene.
	 * @param tipo String (Deportivo, Familiar, 4x4).
	 */
	public CocheElectrico(String matricula, String marca, String modelo, String color, GregorianCalendar fechaAlta, int kms,
			Categoria categoria, Oficina oficina, boolean alquilado, int autonimia, int tiempoRecarga, int n_plazas,
			String tipo) {
		super(matricula, marca, modelo, color, fechaAlta, kms, categoria, oficina, alquilado, autonimia, tiempoRecarga);
		this.n_plazas = n_plazas;
		this.tipo = tipo;
	}

	
	public int getN_plazas() {
		int aux=this.n_plazas;
		return aux;
	}

	public Double getPrecioDiario() {
		Double aux=this.precioDiario;
		return aux;
	}


	public String getTipo() {
		String aux=this.tipo;
		return aux;
	}


	public void setN_plazas(int n_plazas) {
		int aux = n_plazas;
		this.n_plazas = aux;	
	}


	public void setTipo(String tipo) {
		String aux = tipo;
		this.tipo = aux;	
	}

	@Override
	public String toString() {
		return super.toString()+", Número de plazas : " + n_plazas +", Tipo : " + tipo;
	}

	/**
	 * Calcula el precio total a pagar segun las fechas previstas.
	 * @param a Objeto Alquiler para coger las fechas.
	 * @return Precio del alquiler previsto.
	 */
	@Override
	public Double calculaAlquilerPrevisto(Alquiler a) {
		
		//consigo la diferencia de dias de la fecha de inicia y la de fin prevista
		int difDias = miLibreria.metodos.Fechas.difDiasEntreFechas(a.getFechaIniAlquiler(), a.getFechaIniAlquiler());
		
		//calculo el precio total
		Double total = (difDias*precioDiario)+((difDias*precioDiario)*(super.getPorcentajeSubida()/100));
		
		return total;
	}
	
	/**
	 * Calcula el precio total a pagar segun las fechas reales.
	 * @param a Objeto Alquiler para coger las fechas.
	 * @param b Objeto Devolucion para coger las fechas.
	 * @return Precio del alquiler previsto.
	 */
	@Override
	public Double calculaAlquilerReal(Alquiler a, Devolucion b) {
		
		//consigo la diferencia de dias de la fecha de inicia y la de fin prevista
		int difDias = miLibreria.metodos.Fechas.difDiasEntreFechas(a.getFechaIniAlquiler(), b.getFechaDevolucionReal());
		
		//calculo el precio total
		Double total = (difDias*precioDiario)+((difDias*precioDiario)*(super.getPorcentajeSubida()/100));
		
		return total;
	}
	
}
