// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.io.Serializable;
import java.util.*;
/************************************************************/
/**
 * 
 */
//
public class Empleado extends miLibreria.objetos.Persona implements Serializable{

	private GregorianCalendar fechaAlta;
	private Oficina oficina;
	
	/**
	 * @param ap1 String Primer Apellido
	 * @param ap2 String Segundo Apellido
	 * @param nombre String de Nombre de la Persona
	 * @param fechaNac Dato tipo GregorianCalendar con la fecha de nacimiento
	 * @param dni String con el DNI del usuario
	 * @param oficina Objeto Oficina donde trabaja
	 * @param fechaAlta objeto GregorianCalendar de la fecha de alta de trabajo
	 */
	public Empleado(String ap1, String ap2, String nombre, GregorianCalendar fechaNac, String dni, Oficina oficina, GregorianCalendar fechaAlta) {
		super(ap1, ap2, nombre, fechaNac, dni);
		// TODO Auto-generated constructor stub
		this.oficina = oficina;
		this.fechaAlta = fechaAlta;	
	}
	
	public GregorianCalendar getFechaAlta() {
		GregorianCalendar aux=this.fechaAlta;
		return aux;
	}

	public Oficina getOficina() {
		Oficina aux=this.oficina;
		return aux;	
	}

	public void setFechaAlta(GregorianCalendar fechaAlta) {
		GregorianCalendar aux = fechaAlta;
		this.fechaAlta = aux;	
	}

	public void setOficina(Oficina oficina) {
		Oficina aux = oficina;
		this.oficina = aux;	
	}

	@Override
	public String toString() {
		return super.toString()+"\n"
				+"	-Oficina : " + oficina;
	}
	
}
