// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.util.Calendar;
import java.util.GregorianCalendar;

/************************************************************/
/**
 * 
 */
public class Furgoneta extends Combustion{
	private int capacidadCarga;
	private TipoCarnet carnetRequerido;
	
	private Double precioDiario = 70.0;

	/**
	 * Construcor completo de una furgoneta
	 * @param matricula String matriculo vehiculo.
	 * @param marca String marca vehículo.
	 * @param modelo String modelo vehículo.
	 * @param color String color vehículo.
	 * @param fechaAlta Calendar fecha de alta del vehículo en el concesionario.
	 * @param kms Int kilometros que lleva recorrido el vehículo.
	 * @param categoria Categoría categoria del vehículo.
	 * @param oficina Oficina donde se encuentra el vehículo.
	 * @param alquilado Boolean si está o no alquilado.
	 * @param consumo Double del consumo del vehicculo por km.
	 * @param potencia Int potencia del vehículo.
	 * @param nivel_emison String nivel de emision.
	 * @param capacidadCarga int Capacidad carga KG.
	 * @param carnetRequerido String Carnet Requerido (B1, A2...ETC)
	 */
	public Furgoneta(String matricula, String marca, String modelo, String color, GregorianCalendar fechaAlta, int kms,
			Categoria categoria, Oficina oficina, boolean alquilado, int consumo, int potencia, String nivel_emison,
			int capacidadCarga, TipoCarnet carnetRequerido) {
		super(matricula, marca, modelo, color, fechaAlta, kms, categoria, oficina, alquilado, consumo, potencia,
				nivel_emison);
		this.capacidadCarga = capacidadCarga;
		this.carnetRequerido = carnetRequerido;
	}

	
	public int getCapacidadCarga() {
		int aux=this.capacidadCarga;
		return aux;
	}


	public TipoCarnet getCarnetRequerido() {
		TipoCarnet aux=this.carnetRequerido;
		return aux;
	}


	public void setCapacidadCarga(int capacidadCarga) {
		int aux = capacidadCarga;
		this.capacidadCarga= aux;
	}


	public void setCarnetRequerido(TipoCarnet carnetRequerido) {
		TipoCarnet aux = carnetRequerido;
		this.carnetRequerido = aux;
	}

	@Override
	public String toString() {
		return super.toString()+", Capacidad de cargar : " + capacidadCarga+"kg";
	}
	
	/**
	 * Calcula el precio total a pagar segun las fechas previstas.
	 * @param a Objeto Alquiler para coger las fechas.
	 * @return Precio del alquiler previsto.
	 */
	@Override
	public Double calculaAlquilerPrevisto(Alquiler a) {
		
		//consigo la diferencia de dias de la fecha de inicia y la de fin prevista
		int difDias = miLibreria.metodos.Fechas.difDiasEntreFechas(a.getFechaIniAlquiler(), a.getFechaIniAlquiler());
		
		//calculo el precio total
		Double total = (difDias*precioDiario)+((difDias*precioDiario)*(super.getPorcentajeSubida()/100));
		
		return total;
	}
	/**
	 * Calcula el precio total a pagar segun las fechas reales.
	 * @param a Objeto Alquiler para coger las fechas.
	 * @param b Objeto Devolucion para coger las fechas.
	 * @return Precio del alquiler previsto.
	 */
	@Override
	public Double calculaAlquilerReal(Alquiler a, Devolucion b) {
		
		//consigo la diferencia de dias de la fecha de inicia y la de fin prevista
		int difDias = miLibreria.metodos.Fechas.difDiasEntreFechas(a.getFechaIniAlquiler(), b.getFechaDevolucionReal());
		
		//calculo el precio total
		Double total = (difDias*precioDiario)+((difDias*precioDiario)*(super.getPorcentajeSubida()/100));
		
		return total;
	}
}
