// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.io.Serializable;

/************************************************************/
/**
 * 
 */
public class Oficina implements Comparable<Oficina>, Serializable{
	private static final long serialVersionUID = 123456754611133233L;
	private String cod;
	private String descripcion;
	private String localidad;
	private String provincia;
	private boolean ofiAeropuerto;
	
	/**
	 * Constructor completo para oficina.
	 * @param cod String codigo de oficina.
	 * @param descripcion String descripcion de la oficina, ubicación. 
	 * @param localidad String de localidad donde está la oficina.
	 * @param provincia String de provincia donde está la oficina.
	 * @param ofiAeropuerto Boolean si es o no una oficina ubicada en un aeropuerto.
	 */
	public Oficina(String cod, String descripcion, String localidad, String provincia, boolean ofiAeropuerto) {
		super();
		this.cod = cod;
		this.descripcion = descripcion;
		this.localidad = localidad;
		this.provincia = provincia;
		this.ofiAeropuerto = ofiAeropuerto;
	}

	public String getCod() {
		String aux=this.cod;
		return aux;
	}

	public String getDescripcion() {
		String aux=this.descripcion;
		return aux;
	}

	public String getLocalidad() {
		String aux=this.localidad;
		return aux;
	}

	public String getProvincia() {
		String aux=this.provincia;
		return aux;
	}

	public boolean isOfiAeropuerto() {
		boolean aux=this.ofiAeropuerto;
		return aux;
	}

	public void setCod(String cod) {
		String aux = cod;
		this.cod= aux;
	}

	public void setDescripcion(String descripcion) {
		String aux = descripcion;
		this.descripcion= aux;
	}

	public void setLocalidad(String localidad) {
		String aux = localidad;
		this.localidad = aux;
	}

	public void setProvincia(String provincia) {
		String aux = provincia;
		this.provincia = aux;
	}

	public void setOfiAeropuerto(boolean ofiAeropuerto) {
		boolean aux = ofiAeropuerto;
		this.ofiAeropuerto = aux;
	}

	public int compareTo(Oficina a) {
		int devolver=0;
		
		//si localidad y prov son iguales comparo por desc
		if (this.getProvincia().toUpperCase().compareTo(a.getProvincia().toUpperCase())==0 && this.getLocalidad().toUpperCase().compareTo(a.getLocalidad().toUpperCase())==0) {
			devolver=this.getDescripcion().compareTo(a.getDescripcion());
		} //si la provincia es la misma comparo por localidad
		else if (this.getProvincia().toUpperCase().compareTo(a.getProvincia().toUpperCase())==0){
			devolver = this.getLocalidad().toUpperCase().compareTo(a.getLocalidad().toUpperCase()); 
		}//si nada es igual comparo por provincia
		else devolver = this.getProvincia().toUpperCase().compareTo(a.getProvincia().toUpperCase());
		
		return devolver;
	}
	
	@Override
	public boolean equals(Object a) {
		boolean igual = false;
		Oficina b= (Oficina) a;
		
		if (b.compareTo(this)==0) igual = true;
		
		return igual;
    }

	@Override
	public String toString() {
		return cod + ", "+ descripcion + ", " + localidad + ", "+ provincia + ".";
	}

	
	
}
