// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package objetos;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;

/************************************************************/
/**
 * 
 */
public class TipoCarnet implements Serializable{
	private String nombre;
	private String desc;

	
	public TipoCarnet(String nombre, String desc) {
		super();
		this.nombre = nombre;
		this.desc = desc;
	}

	public String getNombre() {
		String aux=this.nombre;
		return aux;
	}

	public String getDesc() {
		String aux=this.desc;
		return aux;
	}

	public void setNombre(String nombre) {
		String aux = nombre;
		this.nombre = aux;
	}

	public void setDesc(String desc) {
		String aux = desc;
		this.desc = aux;
	}

	/**
	 * Graba los datos de la empresa en el archivi "datosEmpresa.ser"
	 */
	public void grabaDatosTiposCarnet() {
		FileOutputStream f = null;
		ObjectOutputStream o = null;
		
		try {
			f = new FileOutputStream ("TiposCarnet.ser");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			o = new ObjectOutputStream(f);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			o.writeObject(this);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Lee datos de la empresa del archivo datosEmpresa.ser
	 */
	public void leeDatosTiposCarnet() {
		FileInputStream f = null;
		ObjectInputStream o = null;
		
		try {
			f = new FileInputStream ("TiposCarnet.ser");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			o = new ObjectInputStream(f);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			o.readObject();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public String toString() {
		return nombre + ", " + desc;
	}
	
	

}
