// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package entidades;

import java.io.Serializable;
import java.util.*;

import miLibreria.objetos.Persona;

/************************************************************/

public abstract class Vehiculo implements Comparable<Vehiculo>, Serializable {
	private static final long serialVersionUID = 12345633327234647L;
	private String matricula;
	private String marca;
	private String modelo;
	private String color;
	private GregorianCalendar fechaAlta;
	private int kms;
	private Categoria categoria;
	private Oficina oficina;
	private boolean	alquilado;
	
	/**
	 * Constructor de un vehículo completo, con todas las propiedades.
	 * @param matricula String matriculo vehiculo.
	 * @param marca String marca vehículo.
	 * @param modelo String modelo vehículo.
	 * @param color String color vehículo.
	 * @param fechaAlta GregorianCalendar fecha de alta del vehículo en el concesionario.
	 * @param kms Int kilometros que lleva recorrido el vehículo.
	 * @param categoria Categoría categoria del vehículo.
	 * @param oficina Oficina donde se encuentra el vehículo.
	 * @param alquilado Boolean si está o no alquilado.
	 */
	
	public Vehiculo(String matricula, String marca, String modelo, String color, GregorianCalendar fechaAlta, int kms,
			Categoria categoria, Oficina oficina, boolean alquilado) {
		super();
		this.matricula = matricula;
		this.marca = marca;
		this.modelo = modelo;
		this.color = color;
		this.fechaAlta = fechaAlta;
		this.kms = kms;
		this.categoria = categoria;
		this.oficina = oficina;
		this.alquilado = alquilado;
	}


	@Override
	//comparo por matricula alfabeticamente.
	public int compareTo(Vehiculo a) {
		int devolver=0;
		//si su marca y modelo es igual, ordeno por matricula
		if (this.getMarca().toUpperCase().compareTo(a.getMarca().toUpperCase())==0 && this.getModelo().toUpperCase().compareTo(a.getModelo().toUpperCase())==0) {
			devolver = this.getMatricula().toUpperCase().compareTo(a.getMatricula().toUpperCase());
		}//si no son iguales, compruebo que la marca es igual para ordenar por modelo.
		else if (this.getMarca().toUpperCase().compareTo(a.getMarca().toUpperCase())==0) {
			devolver = this.getModelo().toUpperCase().compareTo(a.getModelo().toUpperCase());			
		}//si no es igual, ordeno por marca 
		else devolver = this.getMarca().toUpperCase().compareTo(a.getMarca().toUpperCase());			
		
		return devolver;
	}
	
	@Override
	public boolean equals(Object a) {
		boolean igual = false;
		Vehiculo b= (Vehiculo) a;
		
		if (b.compareTo(this)==0) igual = true;
		
		return igual;
	}

	@Override
	public String toString() {
		return this.getMatricula()+", "+this.getMarca()+", "+this.getModelo();
	}

	
	public boolean isAlquilado() {
		boolean aux=this.alquilado;
		return aux;
	}

	public void setAlquilado(boolean alquilado) {
		boolean aux = alquilado;
		this.alquilado = aux;
	}

	public String getMatricula() {
		String aux=this.matricula;
		return aux;
	}

	public String getMarca() {
		String aux=this.marca;
		return aux;
	}

	public String getModelo() {
		String aux=this.modelo;
		return aux;
	}

	public String getColor() {
		String aux=this.color;
		return aux;
	}

	public GregorianCalendar getFechaAlta() {
		GregorianCalendar aux=this.fechaAlta;
		return aux;
	}

	public int getKms() {
		int aux=this.kms;
		return aux;	
	}

	public Categoria getCategoria() {
		Categoria aux=this.categoria;
		return aux;
	}

	public Oficina getOficina() {
		Oficina aux=this.oficina;
		return aux;
	}

	public void setMatricula(String matricula) {
		String aux = matricula;
		this.matricula = aux;
	}

	public void setMarca(String marca) {
		String aux = marca;
		this.marca = aux;
	}

	public void setModelo(String modelo) {
		String aux = modelo;
		this.modelo = aux;
	}

	public void setColor(String color) {
		String aux = color;
		this.color = aux;
	}

	public void setFechaAlta(GregorianCalendar fechaAlta) {
		GregorianCalendar aux = fechaAlta;
		this.fechaAlta = aux;	
	}

	public void setKms(int kms) {
		int aux = kms;
		this.kms = aux;
	}

	public void setCategoria(Categoria categoria) {
		Categoria aux = categoria;
		this.categoria = aux;
	}

	public void setOficina(Oficina oficina) {
		Oficina aux = oficina;
		this.oficina = aux;
	}
		
	public abstract Double calculaAlquilerPrevisto(Alquiler a);
	public abstract Double calculaAlquilerReal(Alquiler a, Devolucion b);
}
